version: "2"
services:

  ###############################################################################
  ############################# -dev-local suffix - #############################
  ##
  ## nginx->php->pgsql
  ## Run this for Easy Development without HTTPS on local machine OR your own AWS
  ##
  ###############################################################################

  nginx-dev-local:
    build:
      context: ./docker/nginx
      args:
        - SERVER_NAME=_
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-dev-local:php
    volumes:
      - "./docker/nginx/letsencrypt:/etc/letsencrypt/:rw"
      - "./docker/nginx/nginxlogs/:/var/log/nginx/:rw"
      - "./public:/var/www/public:rw"
      - "./lib/vendor/symfony/data/web/sf:/var/www/lib/vendor/symfony:ro"

  php-dev-local:
    build:
      context: ./docker/php
      args:
        - display_errors=off
        - log_errors=on
        - site_name=gundeals.local
        - app_env=dev
        - app_secret="devsecretdevsecret_DO_NOT_USE_IN_PROD"
        #- trusted_hosts=localhost
        - trusted_proxies=nginx-dev-local
        - database_url=pgsql://developer:devdevdev@db-dev-local:5432/devdb?serverVersion=9.6
        - no_reply_address="no-reply@example.com"
        - mailer_url="null://localhost"
    expose:
      - '9000'
    links:
      - db-dev-local
    volumes:
      - "./assets:/var/www/assets:rw"
      - "./config:/var/www/config:rw"
      - "./lib:/var/www/lib:rw"
      - "./node_modules:/var/www/node_modules:rw"
      - "./public:/var/www/public:rw"
      - "./scripts:/var/www/scripts"
      - "./src:/var/www/src"
      - "./bin:/var/www/bin"
      - "./templates:/var/www/templates"
      - "./translations:/var/www/translations"
      - "./var:/var/www/var:rw"
      - "./vendor:/var/www/vendor:rw"
      - "./composer.json:/var/www/composer.json"
      - "./composer.lock:/var/www/composer.lock:rw"
      - "./fontello.json:/var/www/fontello.json"
      - "./package.json:/var/www/package.json"
      - "./package-lock.json:/var/www/package-lock.json:rw"
      - "./phpunit.xml.dist:/var/www/phpunit.xml.dist"
      - "./symfony.lock:/var/www/symfony.lock:rw"
      - "./webpack.config.js:/var/www/webpack.config.js"
    working_dir: /var/www/public

  db-dev-local:
    image: postgres:9.6.8
    expose:
      - '5432'
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devdevdev
      POSTGRES_DB: devdb
