version: "2"
services:

  # TODO: -staging and -prod suffix - copy from dev-tree

  ###############################################################################
  ################################ -dev suffix - ################################
  ##
  # Official dev box with HTTPS and shared Development Database
  # Dependency Tree: nginx->php
  # Database: external, URL obtained through AWS SSM with Key setup in php environment
  ##
  ###############################################################################

  nginx-dev:
    build:
      context: ./docker/nginx
      args:
        - HTTPS_CERT_NAME=rgundeals.com
        - SERVER_NAME=dev.rgundeals.com
        - REDIRECT_DOMAINS=rgundeals.com,www.rgundeals.com,gundeals.io,www.gundeals.io
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-dev:php
    volumes:
      - "./docker/nginx/letsencrypt:/etc/letsencrypt/:rw"
      - "./docker/nginx/nginxlogs/:/var/log/nginx/:rw"
      - "./public:/var/www/public:rw"
      - "./lib/vendor/symfony/data/web/sf:/var/www/lib/vendor/symfony:ro"

  # TODO: make this thing work with erb and ssm
  # setup ssm keys
  php-dev:
    build:
      context: ./docker/php
      args:
        - display_errors=off
        - log_errors=off
        - site_name=dev.rgundeals.com
        - app_env=dev
        - app_secret="devsecretdevsecret_DO_NOT_USE_IN_PROD"
        - trusted_hosts=localhost,watob.io
        - aws_ssm_name_db_url=/test/test
        - aws_ssm_region=us-west-2
        - no_reply_address="no-reply@example.com"
        - mailer_url="null://localhost"
    expose:
      - '9000'
    volumes:
        # Maaaan, fuck that shit
      - "./assets:/var/www/assets:rw"
      - "./config:/var/www/config:rw"
      - "./lib:/var/www/lib:rw"
      - "./node_modules:/var/www/node_modules:rw"
      - "./public:/var/www/public:rw"
      - "./scripts:/var/www/scripts"
      - "./src:/var/www/src"
        # no bin
      - "./templates:/var/www/templates"
      - "./translations:/var/www/translations"
      - "./var:/var/www/var:rw"
      - "./vendor:/var/www/vendor:rw"
      - "./composer.json:/var/www/composer.json"
      - "./composer.lock:/var/www/composer.lock:rw"
      - "./fontello.json:/var/www/fontello.json"
      - "./package.json:/var/www/package.json"
      - "./package-lock.json:/var/www/package-lock.json:rw"
      - "./phpunit.xml.dist:/var/www/phpunit.xml.dist"
      - "./symfony.lock:/var/www/symfony.lock:rw"
      - "./webpack.config.js:/var/www/webpack.config.js"
    working_dir: /var/www/public


  ###############################################################################
  ############################# -dev-local suffix - #############################
  ##
  ## Official dev box with HTTPS and shared Development Database
  ## Dependency Tree: nginx->php->pgsql
  ## Run this for Easy Development without HTTPS on local machine OR your own AWS
  ##
  ###############################################################################

  nginx-dev-local:
    build:
      context: ./docker/nginx
      args:
        - SERVER_NAME=dev.rgundeals.com
        - REDIRECT_DOMAINS=rgundeals.com,www.rgundeals.com,gundeals.io,www.gundeals.io
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-dev-local:php
    volumes:
      - "./docker/nginx/letsencrypt:/etc/letsencrypt/:rw"
      - "./docker/nginx/nginxlogs/:/var/log/nginx/:rw"
      - "./public:/var/www/public:rw"
      - "./lib/vendor/symfony/data/web/sf:/var/www/lib/vendor/symfony:ro"

  php-dev-local:
    build:
      context: ./docker/php
      args:
        - display_errors=off
        - log_errors=on
        - site_name=watob.io
        - app_env=dev
        - app_secret="devsecretdevsecret_DO_NOT_USE_IN_PROD"
        - trusted_hosts=localhost,watob.io
        - database_url=pgsql://developer:devdevdev@db-dev-local:5432/devdb?serverVersion=9.6
        - no_reply_address="no-reply@example.com"
        - mailer_url="null://localhost"
    expose:
      - '9000'
    links:
      - db-dev-local
    volumes:
        # Maaaan, fuck that shit
      - "./assets:/var/www/assets:rw"
      - "./config:/var/www/config:rw"
      - "./lib:/var/www/lib:rw"
      - "./node_modules:/var/www/node_modules:rw"
      - "./public:/var/www/public:rw"
      - "./scripts:/var/www/scripts"
      - "./src:/var/www/src"
      - "./bin:/var/www/bin"
      - "./templates:/var/www/templates"
      - "./translations:/var/www/translations"
      - "./var:/var/www/var:rw"
      - "./vendor:/var/www/vendor:rw"
      - "./composer.json:/var/www/composer.json"
      - "./composer.lock:/var/www/composer.lock:rw"
      - "./fontello.json:/var/www/fontello.json"
      - "./package.json:/var/www/package.json"
      - "./package-lock.json:/var/www/package-lock.json:rw"
      - "./phpunit.xml.dist:/var/www/phpunit.xml.dist"
      - "./symfony.lock:/var/www/symfony.lock:rw"
      - "./webpack.config.js:/var/www/webpack.config.js"
    working_dir: /var/www/public
    command: "/devlocal.sh"

  db-dev-local:
    image: postgres:9.6.8
    expose:
      - '5432'
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devdevdev
      POSTGRES_DB: devdb
