version: "2"
services:

  ###############################################################################
  ############################# -dev-local suffix - #############################
  ##
  ## nginx->php->pgsql
  ## Run this for Easy Development without HTTPS on local machine OR your own AWS
  ##
  ###############################################################################

  nginx-dev-local:
    build:
      context: ./docker/nginx
      args:
        - SERVER_NAME=_
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-dev-local:php
    volumes:
      - "./docker/nginx/letsencrypt:/etc/letsencrypt/:rw"
      - "./docker/nginx/nginxlogs/:/var/log/nginx/:rw"
      - "wwwdir:/var/www/:ro"
  php-dev-local:
    build:
      context: .
      args:
        - display_errors=off
        - log_errors=on
        - site_name=gundeals.local
        - app_env=dev
        - app_secret="devsecretdevsecret_DO_NOT_USE_IN_PROD"
        #- trusted_hosts=localhost
        - trusted_proxies=nginx-dev-local
        - database_url=pgsql://developer:devdevdev@db-dev-local:5432/devdb?serverVersion=9.6
        - no_reply_address="no-reply@example.com"
        - mailer_url="null://localhost"
    expose:
      - '9000'
    links:
      - db-dev-local
    volumes:
      - "wwwdir:/var/www:rw"
      - "./bin:/var/www/bin:ro"
    working_dir: /var/www/public

  db-dev-local:
    image: postgres:9.6.8
    expose:
      - '5432'
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devdevdev
      POSTGRES_DB: devdb

volumes:
  wwwdir:

